deg_abstr = {"abstraction":0.8,"architecture":0.3,"emotions, concepts and ideas":0.9,
"history":0.6,"interiors":0.4,"leisure and pastimes":0.8,"literature and fiction":0.7,
"nature":0,"objects":0,"religion and belief":0.5,"society":0.6,"symbols & personifications":1,
"work and occupations":0.7, "people":0, "places":0.2, "movement":1, "from recognisable sources":0.7,
"non-representational":1, "agricultural":0.1,"bridges and viaducts":0,"features":0.4,
"garden structures":0.2,"industrial":0.3,"military":0.3,"monuments":0.2,"periods and styles":0.7,
"places of entertainment":0.4,"public and municipal":0.3,"religious":0.4,"residential":0.1,"ruins":0.1,
"townscapes, man-made features":0.4, "emotions and human qualities":1,"formal qualities":0.8,
"universal concepts":0.9, "arts":0.6,"politics and society":0.7, "domestic":0.4,
"places of entertainment":0.5,"public and municipal":0.4,"religious":0.5,"workspaces":0.3,
"art and craft":0.6,"eating and drinking":0.4,"music and entertainment":0.6,"recreational activities":0.4,
"sport":0.3, "film, music and ballet":0.7,"literature (not Shakespeare)":0.8,
"tales, legends and traditional":0.9, "astronomy":0.4,"landscape":0.3,"natural phenomena":0.4,
"plants and flowers":0.1,"seascapes and coasts":0.1,"seasons":0.3,"times of the day":0.3,"trees":0,
"weather":0.4, "agriculture, gardening & fishing":0.4,"clothing and personal effects":0.4,"domestic":0.3,
"electrical appliances":0.2,"fine art and design, named works":0.7,"fine arts and music":0.7,
"food and drink":0.2,"furnishings":0.1,"heating and lighting":0.2,"kitchen":0.2,"materials":0.3,
"medical":0.3,"miscellaneous":0.8,"reading, writing, printed matter":0.7,"religious and ceremonial":0.6,
"scientific and measuring":0.7,"sports and games":0.6,"tools and machinery":0.6,"toys and models":0.4,
"vessels and containers":0.4,"weapons":0.2, "adults":0.2,"body":0.1,"children":0.2,
"diseases and conditions":0.4,"ethnicity":0.6,"groups":0.3,"named families":0.6,
"named individuals":0.6,"nudes":0.1,"portraits":0, "cities, towns, villages (non-UK)":0.4,
"countries and continents":0.5,"man-made landmarks (non-UK)":0.3,"UK countries and regions":0.5,
"UK London":0.4, "Judaeo-Christian imagery":0.5,"magic and occultism":0.9,"mysticism":1,"Saints":0.3,
"universal religious imagery":0.4,"world religions":0.5, "birth to death":0.9,"crime and punishment":0.7,
"education, science and learning":0.6,"family":0.4,"government and politics":0.5,"health and welfare":0.6,
"lifestyle and culture":0.7,"nationality":0.6,"sex and relationships":0.5,"social comment":0.8,
"abstract concepts":1,"birth to death":0.9,"emotional states and conditions":1,"gender":0.8,
"inscriptions":0.5,"nature":0.8,"religious":0.8,"society":0.9, "agriculture and fishing":0.3,
"arts and entertainment":0.4,"crime and punishment":0.6,"domestic":0.5,"educational and scientific":0.4,
"equestrian and sporting":0.3,"industrial and crafts":0.3,"literary":0.4,"medical":0.3,"military":0.3,
"public service":0.4,"religious":0.5,"royalty and social rank":0.3,"trading and commercial":0.5
};
